codistica/codistica-js

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- configs/babel/babel-plugin-banner.js
- package.json
- packages/codistica-browser/package.json
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/package.json
- packages/codistica-node/package.json
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/package.json
This pull request adds required md files for the monorepo to comply with community standards. Should be rebased before creating further pull requests
> [feature] - Adjust docs to community standards

- package.json
- yarn.lock
> [bugfix] - Husky hooks exit code problem

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> [feature] - Docs and templates update

- .eslintrc.js
- package.json
- yarn.lock
> [feature] - Implement @codistica/eslint-config-default package

- .prettierrc.js
- package.json
- yarn.lock
> [feature] - Implement @codistica/prettier-config-default package

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- .github/workflows/pull-request.yml
- CHANGELOG.md
- README.md
- packages/codistica-browser/README.md
- packages/codistica-core/README.md
- packages/codistica-demo/docs/react-readme.md
- packages/codistica-dev-tools/README.md
- packages/codistica-node/README.md
- packages/codistica-react/README.md
- packages/codistica-scriptfiber/README.md
- packages/codistica-types/README.md
> [feature] - Documentation improvement

- CONTRIBUTING.md
- README.md
- packages/codistica-browser/README.md
- packages/codistica-core/README.md
- packages/codistica-demo/README.md
- packages/codistica-dev-tools/README.md
- packages/codistica-node/README.md
- packages/codistica-react/README.md
- packages/codistica-scriptfiber/README.md
- packages/codistica-types/README.md
> [feature] - Improvements to documentation files

- CHANGELOG.md
- CONTRIBUTING.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-core/CHANGELOG.md
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-node/CHANGELOG.md
- packages/codistica-react/CHANGELOG.md
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-types/CHANGELOG.md
> [feature] - Add CHANGELOG.md files to each package

- .eslintrc.js
> [feature] - Improve ESLint config

- packages/codistica-browser/package.json
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/package.json
- packages/codistica-node/package.json
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/package.json
- @codistica/browser@1.0.0-beta.0
- @codistica/core@1.0.0-beta.0
- @codistica/demo@1.0.0-beta.0
- @codistica/dev-tools@1.0.0-beta.0
- @codistica/node@1.0.0-beta.0
- @codistica/react@1.0.0-beta.0
- @codistica/scriptfiber@1.0.0-beta.0
- @codistica/types@1.0.0-beta.0
* ALL
None.
> [release] - 2020/04/21

- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
> [bugfix] - Types not being published.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
- @codistica/browser@1.0.0-beta.1
- @codistica/core@1.0.0-beta.1
- @codistica/dev-tools@1.0.0-beta.1
- @codistica/node@1.0.0-beta.1
- @codistica/react@1.0.0-beta.1
- @codistica/scriptfiber@1.0.0-beta.1
- @codistica/types@1.0.0-beta.1
* all
None.
> [release] - 2020/04/22.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
> [publish] - 2020/04/22.

- .eslintrc.js
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-react/src/index.js
> [bugfix] - Remove import extensions preventing flow detection.

- CHANGELOG.md
- packages/codistica-demo/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- @codistica/demo@1.0.0-beta.1
- @codistica/react@1.0.0-beta.2
* root
None.
> [release] - 2020/04/23.

- .github/workflows/pull-request.yml
- CHANGELOG.md
- package.json
* root
Addition of Coveralls to the Github actions CI.
> [feature] - Add coverage feedback on pull-requests.

- .github/workflows/pre-release-tags.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-tags.yml
- CHANGELOG.md
- package.json
* root
This addition intends to automate the creation of Git releases. A first step towards automatic publish.
> [feature] - Automate tag creation on release.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
- @codistica/browser@1.0.0-beta.2
- @codistica/core@1.0.0-beta.2
- @codistica/demo@1.0.0-beta.2
- @codistica/dev-tools@1.0.0-beta.2
- @codistica/node@1.0.0-beta.2
- @codistica/react@1.0.0-beta.3
- @codistica/scriptfiber@1.0.0-beta.2
- @codistica/types@1.0.0-beta.2
* All.
None.
> [release] - 2020/05/07.

- CHANGELOG.md
- packages/codistica-demo/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
> [release] - 2020/05/13.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-demo/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
> [release] - 2020/05/16.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
* root
* codistica-core
* codistica-dev-tools
* codistica-scriptfiber
None.
> [release] - 2020/06/01.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react-icons/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
* root
* codistica-core
* codistica-dev-tools
* codistica-react-icons
None.
> [release] - 2020/07/10.

- packages/codistica-demo/package.json
- packages/codistica-react/package.json
> [bugfix] - Wrong dependencies types.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react-icons/CHANGELOG.md
- packages/codistica-react-icons/package.json
- packages/codistica-react-mui/CHANGELOG.md
- packages/codistica-react-mui/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
* root
* codistica-core
* codistica-dev-tools
* codistica-react-icons
* codistica-react-mui
* codistica-scriptfiber
* codistica-types
None.
> [release] - 2020/10/16.

- packages/codistica-node/src/__tests__/modules/file-utils/internals/contains-path.test.js
- packages/codistica-node/src/modules/file-utils/internals/contains-path.js
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/src/components/input-file/index.js
- packages/codistica-react/src/components/input-file/index.module.scss
- packages/codistica-react/src/components/input-file/index.sophistication.js
- packages/codistica-react/src/index.js
- packages/codistica-react/stories/components/input-file/input-file-default.stories.js
- packages/codistica-react/stories/components/input-file/input-file-image.stories.js
> [feature] - Input file.

- CHANGELOG.md
- packages/codistica-browser/CHANGELOG.md
- packages/codistica-browser/package.json
- packages/codistica-core/CHANGELOG.md
- packages/codistica-core/package.json
- packages/codistica-demo/package.json
- packages/codistica-dev-tools/CHANGELOG.md
- packages/codistica-dev-tools/package.json
- packages/codistica-node/CHANGELOG.md
- packages/codistica-node/package.json
- packages/codistica-react-icons/CHANGELOG.md
- packages/codistica-react-icons/package.json
- packages/codistica-react-mui/CHANGELOG.md
- packages/codistica-react-mui/package.json
- packages/codistica-react/CHANGELOG.md
- packages/codistica-react/package.json
- packages/codistica-scriptfiber/CHANGELOG.md
- packages/codistica-scriptfiber/package.json
- packages/codistica-types/CHANGELOG.md
- packages/codistica-types/package.json
* root
* codistica-core
* codistica-dev-tools
* codistica-react-icons
* codistica-react-mui
* codistica-scriptfiber
* codistica-types
None.
> [release] - 2020/11/26.
